---
title: "Modules enrichment"
output: html_notebook
---

```{r}
custom_go_enrich <- function(DEG_results, go_genes, go_names, pv, lfc_th ) {
  if (lfc_th > 0) {
  deg <- DEG_results[(DEG_results$padj<pv) & (DEG_results$log2FoldChange > lfc_th), ] # define DEG genes
  } else {
  deg <- DEG_results[(DEG_results$padj<pv) & (DEG_results$log2FoldChange < lfc_th), ] # define DEG genes
  }
  
  N <- dim(deg)[1]
  go_int <- left_join(deg, go_genes, by = 'Gene')
  
  go_int <- go_int%>% drop_na
  x <- unique(go_int$go)
  generatio_dict <- data.frame(go = c('GO'),
                    M_number = c(1.8))
  for(go_term in x) {
    M <- sum(go_int$go == go_term)
    new_row = c(go = go_term, M_number = M)
    generatio_dict = rbind(generatio_dict,new_row)
  }
  generatio_dict <- generatio_dict[-1,]
  rownames(generatio_dict) <- 1:nrow(generatio_dict)
  
  n <- dim(DEG_results)[1]
  go_all <- left_join(DEG_results, go_genes, by = 'Gene')
  go_all <- go_all%>% drop_na
  bgratio_dict <- data.frame(go = c('GO'),
                    k_number = c(1.8))
  for(go_term in x) {
    k <- sum(go_all$go == go_term)
    new_row = c(go = go_term, k_number = k)
    bgratio_dict = rbind(bgratio_dict,new_row)
  }
  bgratio_dict <- bgratio_dict[-1,]
  rownames(bgratio_dict) <- 1:nrow(bgratio_dict)
  
  df <- merge(generatio_dict, bgratio_dict, by='go')
  rownames(df) <- df$go
  df <- subset(df, select=-c(go))
  
  df <- mutate_all(df, function(x) as.numeric(as.character(x)))
  M <- df$M_number
  k <- df$k_number
  args.df <- data.frame(numWdrawn=M-1, ## White balls drawn
                        numW=k,        ## White balls
                        numB=n-k,      ## Black balls
                        numDrawn=N)    ## balls drawn
  
  ## calculate pvalues based on hypergeometric model
  pvalues <- apply(args.df, 1, function(n)
                   phyper(n[1], n[2], n[3], n[4], lower.tail=FALSE))
  ## gene ratio and background ratio
  GeneRatio <- apply(data.frame(a=M, b=N), 1, function(x)
                     paste(x[1], "/", x[2], sep="", collapse="")
                     )
  BgRatio <- apply(data.frame(a=k, b=n), 1, function(x)
                   paste(x[1], "/", x[2], sep="", collapse="")
                   )
  Over <- data.frame(go = rownames(df),
                     GeneRatio = GeneRatio,
                     BgRatio = BgRatio,
                     pvalue = pvalues)
  
  p.adj <- p.adjust(Over$pvalue, method="BH")
  Over <- data.frame(Over,
                     p.adjust = p.adj)
  
  Over_annot <- left_join(Over, go_names, by = 'go')
  
  return(Over_annot[Over_annot$p.adjust<0.05,])
}
```

```{r}
custom_go_from_list <- function(deg, go_genes, go_names) {
  
  N <- dim(deg)[1]
  go_int <- left_join(deg, go_genes, by = 'Gene')
  
  go_int <- go_int%>% drop_na
  x <- unique(go_int$go)
  generatio_dict <- data.frame(go = c('GO'),
                    M_number = c(1.8))
  for(go_term in x) {
    M <- sum(go_int$go == go_term)
    new_row = c(go = go_term, M_number = M)
    generatio_dict = rbind(generatio_dict,new_row)
  }
  generatio_dict <- generatio_dict[-1,]
  rownames(generatio_dict) <- 1:nrow(generatio_dict)
  
  n <- dim(go_genes)[1]
  go_all <- go_genes
  go_all <- go_all%>% drop_na
  bgratio_dict <- data.frame(go = c('GO'),
                    k_number = c(1.8))
  for(go_term in x) {
    k <- sum(go_all$go == go_term)
    new_row = c(go = go_term, k_number = k)
    bgratio_dict = rbind(bgratio_dict,new_row)
  }
  bgratio_dict <- bgratio_dict[-1,]
  rownames(bgratio_dict) <- 1:nrow(bgratio_dict)
  
  df <- merge(generatio_dict, bgratio_dict, by='go')
  rownames(df) <- df$go
  df <- subset(df, select=-c(go))
  
  df <- mutate_all(df, function(x) as.numeric(as.character(x)))
  M <- df$M_number
  k <- df$k_number
  args.df <- data.frame(numWdrawn=M-1, ## White balls drawn
                        numW=k,        ## White balls
                        numB=n-k,      ## Black balls
                        numDrawn=N)    ## balls drawn
  
  ## calculate pvalues based on hypergeometric model
  pvalues <- apply(args.df, 1, function(n)
                   phyper(n[1], n[2], n[3], n[4], lower.tail=FALSE))
  ## gene ratio and background ratio
  GeneRatio <- apply(data.frame(a=M, b=N), 1, function(x)
                     paste(x[1], "/", x[2], sep="", collapse="")
                     )
  BgRatio <- apply(data.frame(a=k, b=n), 1, function(x)
                   paste(x[1], "/", x[2], sep="", collapse="")
                   )
  Over <- data.frame(go = rownames(df),
                     GeneRatio = GeneRatio,
                     BgRatio = BgRatio,
                     pvalue = pvalues)
  
  p.adj <- p.adjust(Over$pvalue, method="BH")
  Over <- data.frame(Over,
                     p.adjust = p.adj)
  
  Over_annot <- left_join(Over, go_names, by = 'go')
  
  return(Over_annot)
}
```


```{r}
go_genes <- read.table('/scratch/okhtienk/gomap_gene.tsv', header = TRUE, fill=TRUE)
go_names <- read.csv('/scratch/okhtienk/gomap_go_names.csv', header = TRUE, fill=TRUE)
```

#red module. Includes putative lexA

```{r}
deg <- read_table('/scratch/okhtienk/modules_final/merged/colors/module_merged_red.txt', col_names=FALSE)
colnames(deg) <- c("Gene")
df <- custom_go_from_list(deg, go_genes, go_names)
```

```{r}
df[df$p.adjust<0.05,]
```

```{r}
df
```

```{r}
gomap <- data.frame(GO=go_genes$go, Gene=go_genes$Gene)
```

```{r}
deg <- read_table('/scratch/okhtienk/modules_final/merged/colors/module_merged_turquoise.txt', col_names=FALSE)
colnames(deg) <- c("Gene")
```


```{r}
library(clusterProfiler)

enrich_up <- enricher(
  gene=deg$Gene,
  pvalueCutoff = 0.05,
  pAdjustMethod = "BH",
  minGSSize = 1,
  maxGSSize = 500,
  TERM2GENE = gomap,
  TERM2NAME = go_names
)
```

```{r}
summary(enrich_up)
```


```{r}
deg <- read_table('/scratch/okhtienk/modules_final/merged/colors/module_merged_turquoise.txt', col_names=FALSE)
colnames(deg) <- c("Gene")
df <- custom_go_from_list(deg, go_genes, go_names)
df[df$p.adjust<0.05,]
```

